### ISSUE TITLE
Release layout

### ISSUE THREAD

**Issue by montyanderson** [montyanderson/music-nft-app#5]
Put the main release body in a container which takes up the whole width except for the sidebar.
Then make everything inside width: 100%;. This will fix our strange table issues.

No flex needed.

![image](https://user-images.githubusercontent.com/3048503/110737364-27ea4f00-8225-11eb-9484-3c29f35328c9.png)

**Comment by OliverRedman** [comment]
By table issue are you referring to the fact that the lines below/above tracks don't stretch across the entire width?
that is caused by this
<img width="321" alt="Screenshot 2021-03-11 at 10 23 24" src="https://user-images.githubusercontent.com/72112325/110772860-fccb2400-8253-11eb-981a-4c2850014d8b.png">
